-- MySQL Script generated by MySQL Workbench
-- Mon Jun 11 17:10:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unidad` INT NOT NULL,
  `preguntas` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta` (
  `id` INT NOT NULL,
  `pregunta_id` INT NOT NULL,
  `opcion` VARCHAR(45) NOT NULL,
  `correcta` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuesta_pregunta_idx` (`pregunta_id` ASC),
  CONSTRAINT `fk_respuesta_pregunta`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `mydb`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `pregunta_id` INT NOT NULL,
  `unidad_comp` INT NULL,
  `puntaje` INT NULL,
  `logro_comp` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calificacion_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_calificacion_pregunta1_idx` (`pregunta_id` ASC),
  CONSTRAINT `fk_calificacion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `mydb`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `cel` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_personal_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logros` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logros_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_logros_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logros_has_calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logros_has_calificacion` (
  `logros_id` INT NOT NULL,
  `calificacion_id` INT NOT NULL,
  PRIMARY KEY (`logros_id`, `calificacion_id`),
  INDEX `fk_logros_has_calificacion_calificacion1_idx` (`calificacion_id` ASC),
  INDEX `fk_logros_has_calificacion_logros1_idx` (`logros_id` ASC),
  CONSTRAINT `fk_logros_has_calificacion_logros1`
    FOREIGN KEY (`logros_id`)
    REFERENCES `mydb`.`logros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logros_has_calificacion_calificacion1`
    FOREIGN KEY (`calificacion_id`)
    REFERENCES `mydb`.`calificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logros_has_calificacion1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logros_has_calificacion1` (
  `logros_id` INT NOT NULL,
  `calificacion_id` INT NOT NULL,
  PRIMARY KEY (`logros_id`, `calificacion_id`),
  INDEX `fk_logros_has_calificacion1_calificacion1_idx` (`calificacion_id` ASC),
  INDEX `fk_logros_has_calificacion1_logros1_idx` (`logros_id` ASC),
  CONSTRAINT `fk_logros_has_calificacion1_logros1`
    FOREIGN KEY (`logros_id`)
    REFERENCES `mydb`.`logros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logros_has_calificacion1_calificacion1`
    FOREIGN KEY (`calificacion_id`)
    REFERENCES `mydb`.`calificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
